### ISSUE TITLE
Can't make it work with Home Assistant

### ISSUE THREAD

**Issue by Hammerhand17** [giovaboy/ZeppOS-HTTP-Buttons#1]
Hello, I'm trying to use your wonderful app but I'm definitely doing something wrong, maybe you can help me:

I have configured four variables:

HA_ADDR: (my https address)
HA_TOKEN: (my Home Assistant token)
par1: automation.trigger
par2: {"entity_id": ["automation.llegada_a_casa_tasker"]}

Now, I defined one button:

URL: {HA_ADDR}/api/services/{par1}
Method: POST
Headers: Authorization:Bearer {HA_TOKEN}
Body: {par2}

I'm using this same configuration in tasker and it works, but in your app I receive 404 not found. The only difference is that in tasker I'm using a json with this format:
 
```
{
  "entity_id": [
    "automation.llegada_a_casa_tasker"
  ]
}
```

Can you please help me?

And another question, is it necessary to have wifi on in the watch for the button to work? I've tried both with it on and off, but took same result.

Thanks for your work.

**Comment by giovaboy** [comment]
Hi.
Can you please test it without using the parameters function? 
Especially the BODY part, try it by setting it directly.

You don't need Wifi to be enabled on your watch, what is needed it's the connection between watch and phone.

**Comment by Hammerhand17** [comment]
> Hi. Can you please test it without using the parameters function? Especially the BODY part, try it by setting it directly.
> 
> You don't need Wifi to be enabled on your watch, what is needed it's the connection between watch and phone.

Tried to set everything up directly instead of using variables, but how do I set the body part directly is I don't use the Body section?

**Comment by Hammerhand17** [comment]
When I use this raw setup it works, but all the interface to setup the app in zepp application dissapears and I have to uninstall and install it again.

`[{"variables":{},"pages":[{"rows":[{"h":100,"buttons":[{"text":"SPACER","spacer":true,"w":"30","request":{}},{"text":"Click","spacer":false,"w":"40","request":{"method":"POST","url":"https://myhomecoms/api/services/automation/trigger","response_style":0,"headers":{"Authorization":"Bearer MyToken","Content-Type":"application/json"},"body":{"entity_id":"automation.task"}}}]}]}]}]`

**Comment by giovaboy** [comment]
Ok, thanks.
Currently, variables only apply to the URL property. However, I'm going to change this and provide variables for other properties as well.

In the meantime, you can try enclosing HEADERS and BODY in double quotes:

`"headers":"{"Authorization":"Bearer MyToken","Content-Type":"application/json"}","body":"{"entity_id":"automation.task"}"`

**Comment by Hammerhand17** [comment]
I tried as you said:

[{"variables":{},"pages":[{"title":"Home Assistant","rows":[{"h":100,"buttons":[{"text":"SPACER","spacer":false,"w":"30","radius":70,"request":{"headers":"{\"Authorization\":\"Bearer MyToken\",\"Content-Type\":\"application/json\"}","body":"{\"entity_id\":\"automation.task\"}","method":"POST","url":"https://MyHouse.es/api/services/automation/trigger"}}]}]}]}]

I keep receiving 401: Unauthorized

**Comment by Hammerhand17** [comment]
Could you please take a look into it? I've been struggling with all the combinations that came to my mind and couldn't get it working, except:

[{"variables":{},"pages":[{"rows":[{"h":100,"buttons":[{"text":"SPACER","spacer":true,"w":"30","request":{}},{"text":"Click me!","spacer":false,"w":"40","request":{"method":"POST","url":"https://myhouse.com/api/services/automation/trigger","response_style":0,"headers":{"Authorization":"Bearer mytoken","Content-Type":"application/json"},"body":{"entity_id":"automation.task"}}}]}]}]}]

In this one, the button in the watch works, but all the configuration interface in the phone dissapears and I have to uninstall and install again the app. Where is the mistake?

**Comment by giovaboy** [comment]
Try this: `[{
    "variables": {},"pages":[{
        "rows":[{
            "h":100,"buttons":[{
                "text":"SPACER","spacer":true,"w":"30","request": {}}, {
                "text":"Click me!","spacer":false,"w":"40","request": {
                    "method":"POST","url":"https://myhouse.com/api/services/automation/trigger","response_style":0,
                    "headers":"{\"Authorization\":\"Bearer mytoken\",\"Content-Type\":\"application/json\"}",
                    "body":"{\"entity_id\":\"automation.task\"}"
                }}]}]}]}]`

**Comment by Hammerhand17** [comment]
Same result: 401: Unauthorized

**Comment by napukmaxep** [comment]
@giovaboy, Hi!
Tried to investigate and intercepted the request via proxy. There are no any custom headers at all. Actually I don't sure about proper headers syntax, but any attempt produced no custom headers in final request.

**Comment by Hammerhand17** [comment]
> @giovaboy, Hi! Tried to investigate and intercepted the request via proxy. There are no any custom headers at all. Actually I'm not sure about proper headers syntax, but any attempt produced no custom headers in final request.

Besides, the setup I provided in my latest post works but screen goes black. Could you try something like this to see if there are headers? 

I think it does because it works for me

**Comment by napukmaxep** [comment]
> > @giovaboy, Hi! Tried to investigate and intercepted the request via proxy. There are no any custom headers at all. Actually I'm not sure about proper headers syntax, but any attempt produced no custom headers in final request.
> 
> Besides, the setup I provided in my latest post works but screen goes black. Could you try something like this to see if there are headers?
> 
> I think it does because it works for me

R u sure the double quotes r not escaped in you raw configuration?

**Comment by Hammerhand17** [comment]
The only way I got it to work is exactly this: 

`[{"variables":{},"pages":[{"rows":[{"h":100,"buttons":[{"text":"SPACER","spacer":true,"w":"30","request":{}},{"text":"Click me!","spacer":false,"w":"40","request":{"method":"POST","url":"https://myhouse.com/api/services/automation/trigger","response_style":0,"headers":{"Authorization":"Bearer mytoken","Content-Type":"application/json"},"body":{"entity_id":"automation.task"}}}]}]}]}]`

All other tries got 401: unauthorized

**Comment by napukmaxep** [comment]
Yup. It makes app non-configurable, but it works

**Comment by giovaboy** [comment]
![immagine](https://github.com/giovaboy/ZeppOS-HTTP-Buttons/assets/6849800/da29169a-bbbd-478c-8ef7-75d20fc8ba13)
@Hammerhand17 Can you try please with this preview build? Use the configuration as I wrote in my last comment.

**Comment by giovaboy** [comment]
@Hammerhand17 @napukmaxep 
Version 1.2.0 is now available through the Zepp application: can you confirm that this update resolves the issue?

You should also be able to use variables in headers and body definitions.

**Comment by Hammerhand17** [comment]
Yes, it does resolve the issue. With latest 1.2.0. I have configured three buttons which work perfectly. Thanks again for your work!!
