### ISSUE TITLE
Issue with application settings

### ISSUE THREAD

**Issue by barafel1** [giovaboy/ZeppOS-HTTP-Buttons#2]
I tried making something to use with discord webhook, and it works, but when i input this configuration the settings in the app turn into blank page, the watch works but i need to redownload if i wanna change something 
Here's the json
```
```[
  {
    "variables": {
      "var1": "1",
      "var2": "2"
    },
    "pages": [
      {
        "rows": [
          {
            "h": 100,
            "buttons": [
              {
                "text": "SPACER",
                "spacer": true,
                "w": "30",
                "request": {}
              },
              {
                "text": "Click me!",
                "spacer": false,
                "w": "40",
                "request": {
                  "method": "POST",
                  "url": "webhook link",
                  "response_style": 1,
                  "headers": {"Content-Type": "application/json"},
                  "body": {"content": "123abc"}
                }
              }
            ]
          }
        ]
      }
    ]
  }
]
```
![Screenshot_2024-04-29-12-20-07-66_d7d537cedd36783e7cb269073b6348cb](https://github.com/giovaboy/ZeppOS-HTTP-Buttons/assets/65419773/9c5000fd-68d8-4f51-8c19-75302e374abb)

Any idea how to fix ?

**Comment by Hammerhand17** [comment]
Seems to be the same issue I have on the other issue request (don't know how to reference it, sorry)

**Comment by giovaboy** [comment]
As @Hammerhand17 wrote, the issue #1 is due the same problem.
